### ISSUE TITLE
Too many autoloads

### ISSUE THREAD

**Issue by Ughuuu** [foxssake/netfox#141]
Can you limit the creation of autoload to just 1 or less? And have them named something that makes it obvious they are part of Netfox? Right now, Noray, PacketHandshake, NetworkTime, NetworkTimeSynchronizer, NetworkRollback, NetworkEvents, Interpolators. It's not immediately obvious why they are all needed and can't be nodes or static classes. I'll have to check. But even if they are all needed, you can make just 1 singleton that contains the other. Eg:
Netfox:
- Noray
- PacketHandshake
- NetworkTime
..

So you would access them as: Netfox.Noray, Netfox.NetworkTime.. This way it won't pollute the global namespace as much with Classes that have very generic name(the name will start with Netfox, which is add-on name).

**Comment by elementbound** [comment]
Fair enough! So these are all the current autoloads used by all three addons:
- Noray - can be a regular class
- PacketHandshake - can be static
- NetworkTime - needed for RPC + easy to refer to
- NetworkTimeSynchronizer - can be a regular class
- NetworkRollback - needed to make it easy to refer to
- NetworkEvents - needed to make it easy to refer to
- Interpolators - can be static

In terms of names, some of these are intended to be easily referred to, so I would like to avoid putting them under a singleton ( although it's a cool idea! ). Renaming could work though, for example NetfoxTime instead of NetworkTime. Interpolators could also get a prefix.
For PacketHandshake, I think it's specific enough to be ok as-is, but let me know your thoughts.

Some of these would be breaking changes, so I'd only introduce them in v2. First, I would like to see how much interest is there in this change. Let me know whether this is a minor annoyance or a deal-breaker for you! I'll give this a bit of time for other people to chime in too.

**Comment by Ughuuu** [comment]
It's fine also how it is, I'm just thinking about it before some people have problems with it. It's sad that Godot doesn't have namespaces so this happens(name collision). And the more classes you have, the bigger chances this might happen.

Noray can be a regular class, that's the only one I am interested in right now(needed for the signals). However, as you say, making it a class will break stuff as people use it as a singleton right now(or autoload).

It's just kinda strange having so many autoloads from 1 single plugin. I guess if it had the prefix it would make more sense and would be much easier to look through them. Right now if I want to use a class that I autoload, I have to fight with these also polluting the global namespace.

**Comment by elementbound** [comment]
Yeah, I won't hold my breath for namespaces :slightly_smiling_face: 

Good catch on the class names! Will keep this conversation as reference for the eventual renames, I'm leaning towards 2 as well.

Closing issue.
