### ISSUE TITLE
Possibility to choose log level and what to log

### ISSUE THREAD

**Issue by Ughuuu** [foxssake/netfox#149]
Right now in the package there are a lot of prints happening(eg. during connection, etc). Would be cool if there would be a way to only log errors or info logs.

The option could also be a project setting.

**Comment by elementbound** [comment]
A good idea and something I've considered during development! I ended up rejecting it because I didn't want to ship a logging library as part of netfox, and didn't want to introduce external dependencies.

But the concern is valid, and I think a minimal implementation is OK. Will get back to it with a PR.

**Comment by elementbound** [comment]
Hey @Ughuuu,
I've created #162 for this. I ended up creating a "netfox.internals" addon for shared under-the-hood tidbits used by all modules. This for now includes logging, but there's one or two things I can move there in the future.

Pros:
- No code duplication
- Logging configurable per addon ( i.e. no logging from extras, only debug from noray, etc. ):
  ![image](https://github.com/foxssake/netfox/assets/4706096/b543049e-53d8-4321-a274-0b48ccb565b4)

Cons: 
- One extra addon to install per netfox project

Technically, the extra addon shouldn't be much of an issue, since the asset library should handle it well, but let me know what you think.

**Comment by Ughuuu** [comment]
My only concern would be what happens if you update an add-on, how would you version the other directory. I would search to see if there are other cases where they have dependencies like this, maybe you can add a plugin cfg file to version also the internals?
