### ISSUE TITLE
VoIP integration ?

### ISSUE THREAD

**Issue by zarocksx** [foxssake/netfox#158]
Hi,

Is VOIP ( Voice Over IP) planned to be intagrated through Netfox ?

thanks

**Comment by elementbound** [comment]
Fair points @albertok. That's why I'm not planning to build it as an addon, but only as an example. Also it's pretty much the simplest you can go - it uses Godot's builtin audio functionality and does minimal processing.

**Comment by elementbound** [comment]
Created a sample repo, but keep in mind that it's experimental, so there's not much support planned. It's more of a showcase of how you could start on something like this :slightly_smiling_face: 

https://github.com/foxssake/netfox-voip-example

**Comment by goatchurchprime** [comment]
Maybe look at this again as https://github.com/goatchurchprime/two-voip-godot-4 seems to be running pretty well.

With some technical encouragement I'd be motivated to pull the management code surrounding voip (voice threshold, audio balancing and jitter-buffering) down from my much simpler multiplayer system such as [this module](https://github.com/goatchurchprime/godot_multiplayer_networking_workbench/blob/main/addons/player-networking/RecordingFeature.gd) into the base two-voip addon so that you can use it here with the minimum of effort.

**Comment by elementbound** [comment]
@goatchurchprime I've been keeping an eye on this 😄 I have a project planned to try it, will contact you once I eventually get there!
