### ISSUE TITLE
Remove clouds for double the FPS

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#181]
When I open 3 instances, on the UI menu (host/join) I get 106-120 FPS on each instance.
Once I remove the 16 cloud instances and the AABB movement of the clouds, I get 204-212 FPS

Since this is a demo for netfox, I think the clouds should be removed OR keep very few. I find them useful for example, because I didn't know about aura mesh, which I will use for a smoke grenade of sorts. Anyway, low FPS for a demo is just worrying for any new user, because it makes the new users think its the netfox plugin instead of the scene setup.

**Comment by elementbound** [comment]
Hi @TheYellowArchitect,

I'm not sure I follow what's the issue, since based on your report, the example game runs at 100ish fps in *three* instances, which sounds pretty ok since 60Hz displays are the most common afaik.

I get your point about having low fps in a demo, but also having a demo that looks bland / ugly also won't inspire too many people imo. So I think the example game is in a good balance here, but I'd like to stress that I'm open for discussion on this.

**Comment by TheYellowArchitect** [comment]
> the example game runs at 100ish fps in three instances, which sounds pretty ok since 60Hz displays are the most common afaik.

Low-end pcs won't have 100 FPS with 3 or 4 instances, but lower. My pc isn't high-end, but I assume a thinkpad laptop would get sub-60 FPS.

>but also having a demo that looks bland / ugly

I agree. Filmic tonemap (below)
![filmic](https://github.com/foxssake/netfox/assets/25630803/89bbcb4a-b478-4060-99b0-cfebfcda9c7c)
is superior to linear tonemap (below)
![linear](https://github.com/foxssake/netfox/assets/25630803/b5c7c9dc-7df4-4eba-a3a4-ff9cba1f9113)

But this doesn't mean you can't strike a balance with both. The clouds being AABB is overkill. They don't enter the game area at all, so there is no reason to have **volume**. Could be billboard sprites. The clouds alone are heavier than the entire netfox code logic, and that is injustice to this addon.

Like, I cannot believe I found this randomly. I was planning to make my own state rollback engine, thinking it would take a month, but reading the code (e.g. latency compensation), I realize I would fall in many pitfalls I never considered. I am still reading the logic (and will be reading) as I plan to start using this next month for my game (tl;dr: topdown scifi but with rare timetravel via rollback), and the demo **initially** looks underwhelming to the new user who hasn't seen the code. Also no video series or anything intuitive, so the demo must shine. Seeing around 100 FPS on such a basic scene is just bad first impressions :(

Anyway, kinda went off-topic there. To return on-topic, tl;dr: I suggest transparent billboard cloud sprites, same visual results, higher FPS.

**Comment by TheYellowArchitect** [comment]
>The clouds are not AABB's - there's a cloud area script that moves the clouds around in an AABB, making sure to respawn them at the other end as they exit. The reason for that is to easily adjust the cloud area from the editor.

You are right, I just checked :+1: 
No idea why AuraSphereMesh tanks the framerate so hard, ah well it's outside the scope of this project

>I'm also dogfooding with netfox and building my own game on top of it 🙂 I'm planning to put that game on hold a bit soon to apply some upgrades to netfox.

idk what dogfooding is, but I'm glad to hear it. The main reason open-source projects created by a single person die, is when the creator does not benefit from them, aka does not use them or wants them improved. Godot is the obvious example (initially a recycleable game engine) but there are so many others. Generally I'm happy to hear this is still getting attention from its very creator, as it's already complete and functional :)

>Could you please elaborate on this?

The FPS issue mostly xaxaxa
Also, the rollback is not obvious to the user, e.g. RTT and other tags aren't intuitive, as in, it's not clear what they are until some1 looks at the code. This can be solved by a tooltip or full-name. As for rollback, I guess have a phantom VFX, ala symphony of the night? It would highlight visually. Though not sure on this, haven't yet got into the part where there is a literal state rollback on the client-side

For the "instant local action" part (prediction), a bomb is required for example to be crystal clear to the user (even at 100+ ms its instant!),  and even jumping isn't intuitive since the game is top-down and there is no spacebar prompt

>It would be a shame if there was no [documentation](https://foxssake.github.io/netfox/), especially one that goes through [concepts](https://foxssake.github.io/netfox/netfox/concepts/servers-clients-ownership/), [guides for major systems](https://foxssake.github.io/netfox/netfox/guides/network-time/), and even some [tutorials](https://foxssake.github.io/netfox/netfox/tutorials/responsive-player-movement/) to get started 🙂

I never said there is no documentation. What exists is surely appreciative (I wouldn't use netfox if I saw there is no documentation)
Even having read the existing documentation, I am not confident enough to make my own tweaks on it (rollback while a game is going on, basically dynamic replay system) or implement netfox as is on my game (even with documentation, I do not know how to rollback a destroyed projectile)
I have to admit I am spoiled because I came from snopek's rollback addon https://www.youtube.com/watch?v=zvqQPbT8rAE&list=PLCBLMvLIundBXwTa6gwlOUNc29_9btoir
Previous framework I used to release a game on steam was https://github.com/BeardedManStudios/ForgeNetworkingRemastered which had this video-guide https://www.youtube.com/watch?v=feLUmzaogCk&list=PLm1w78-UUlMIi5Vfwy6ckJQIQMHMT-QS5&index=3
Generally, video-guides (atop documentation for specific stuff) are great to get started and avoid some trial&error.
Anyway, I know it takes time to create these, but it would attract tons of users. Think of Jolt, it wouldn't be "the default 3D physics engine" if not for the multiple videos reporting the insane performance gains (and no jitter), alongside multiple installation guides.

**Comment by TheYellowArchitect** [comment]
I thought of this more. The solution is simple. When the label value hits the cap (240), append the string "(Capped)"
So the label value doesn't show "240" but "240 (capped)" and that's it.

**Comment by elementbound** [comment]
> No idea why AuraSphereMesh tanks the framerate so hard, ah well it's outside the scope of this project

From what I've found, it's probably a combination of polycount and overdraw. I suspected proximity fade on the material too, but that did not have much effect.

> idk what dogfooding is, but I'm glad to hear you are using netfox.

It's just that :slightly_smiling_face: Dogfooding is [using your own product](https://en.wikipedia.org/wiki/Eating_your_own_dog_food).

> I lost months of work as that netcoding framework got archived by its creator... So I'm beyond happy to hear this is still getting attention from its very creator

Really sorry to hear about that :disappointed: Yeah, netfox is guaranteed to get attention for this year, as I need it to finish my game! Probably more, since I don't intend to abandon the addon, and there's also more games I plan to build with it.

> Also, the rollback is not obvious to the user, e.g. RTT and other tags aren't intuitive, as in, it's not clear what they are until some1 looks at the code

Yeah, these were built with the expectation of the user already being somewhat familiar with networking, and they are looking for a higher level solution. Hence no explanation on what RTT is, as I expected the target audience to be familiar with it. Same for rollback. But it's also true that less experienced people can also engage with the addons. Let's see if this comes up with more people too - if there's a need from potential users, a toggleable history visualization mode can work.

> Even having read the existing documentation, I am not confident enough to make my own tweaks on it (rollback while a game is going on, basically dynamic replay system) or implement netfox as is on my game (even with documentation, I do not know how to rollback a destroyed projectile)

You're always welcome to post a question under the Discussions tab if you get stuck with something! I still don't follow tho, is there something you did not find in the documentation? Is something missing? Even if there were video tutorials, they would contain the same info as the docs, just in a different format.

> I have to admit I am spoiled because I came from [snopek's rollback addon](https://www.youtube.com/watch?v=zvqQPbT8rAE&list=PLCBLMvLIundBXwTa6gwlOUNc29_9btoir)

Thanks for mentioning Snopek! I've seen his addon while researching, I'm not even aware of any other alternatives to his work.

**Comment by TheYellowArchitect** [comment]
>Even having read the existing documentation, I am not confident enough to make my own tweaks on it (rollback while a game is going on, basically dynamic replay system)

> still don't follow tho, is there something you did not find in the documentation? Is something missing?

I want this https://www.youtube.com/watch?v=VOas6EFJ9X4&pp=ygUJY2hyb25vY2Ft but online/realtime.
The above also requires rollback on animation tree/player, and sound effects.

Also, for all rollback ticks which are considered old and to delete, to instead store them in a byte array (both input, and states)

Anyway, still experimenting, hacking away at code :P
