### ISSUE TITLE
Investigate multiple RPCs being triggered instead of 1

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#184]
```gdscript
# Cache the synced clients, as the rpc call itself may arrive multiple times
# ( for some reason? )
var _synced_clients = {}
```

In the class `network_time.gd` is the above. How can I test this in order to find the root, and help in solving it?
Perhaps this problem doesn't persist in Godot 4.2

**Comment by elementbound** [comment]
Confirming in Godot 4.2 helps indeed! Otherwise, I'd probably just try to step through the process with the debugger to see if there's anything fishy going on or if it's an engine quirk. IIRC at the time of writing I did not see any red flag with the code - which can be deceiving as I wrote all of it :slightly_smiling_face: - and it was not that much of a dealbreaker to start investigating a potential engine quirk.

Either way, I agree that this should not happen in an ideal case, so will look into it. If you happen to find anything, please keep me posted, thanks!
