### ISSUE TITLE
Raycast shooting

### ISSUE THREAD

**Issue by P5ina** [foxssake/netfox#232]
Hello, I have a question. How can I implement raycast shooting mechanics with lag compensation using RollbackSynchronizer. I want to rollback all players, then fire raycast and then resimulate all players again.

**Comment by elementbound** [comment]
Hi @P5ina,

There's currently no dedicated method to do a manual rollback, but you can do it by emitting a network rollback event manually by doing this: `NetworkRollback.on_prepare_tick.emit(tick)`

This will revert the whole game state to the given tick. Make sure to "revert" to the current tick after you're done with your rollback logic. Make sure to consider where you're calling the above from - if it's from the rollback loop itself, you'll need to save `NetworkRollback.tick`'s value, otherwise you can use `NetworkTime.tick` to "revert" to the current tick. 

---

Alternatively, if you want to run the full simulation from a given tick, you can call `NetworkRollback.notify_resimulation_start(tick)` with the tick where you need to do the raycast. Make sure to do this in response to the `NetworkRollback.before_loop` signal. This will make sure that the rollback tick loop includes the tick of the raycast. This needs to be done consistently on every loop, until your raycast tick is too far in the past for a resimulation. 

You can use `NetworkRollback.history_limit` to see if the raycast is too far in the past - if it's older than `history_limit` ticks, it's too old.

Let me know if this makes sense!

**Comment by P5ina** [comment]
@elementbound Thank you so much for the response. It's very helpful, I will try to that.

**Comment by elementbound** [comment]
Hey @P5ina, I'm closing this issue, but feel free to open another if you get stuck on anything else, or join our [Discord](https://discord.gg/xWGh4GskG5) if  you haven't already!
