### ISSUE TITLE
Using global rand functions can have bad results if the user attempts to use `seed(...)`

### ISSUE THREAD

**Issue by Lexari0** [foxssake/netfox#238]
`NetworkWeapon._generate_id(...)` calls `randi_range(...)` for selecting random characters. This would normally be fine, but if a user attempts to use `seed(...)` to intentionally generate the same random values all peers it'll end up re-using the same values.

Using a `RandomNumberGenerator` (initialized with `randomize()`) to always maintain a seed unique from others' code and expectations is recommended (also for the user, so this is half on me :wink:).

**Comment by BtheDestroyer** [comment]
Follow-up to this: `NetworkWeapon._save_projectile()` does no checks to see if the id is already taken.

**Comment by Lexari0** [comment]
Follow-up to this: `NetworkWeapon._save_projectile()` does no checks to see if the id is already taken.

**Comment by elementbound** [comment]
There's some design discussions still up in the air, but in the meantime #270 should fix this. 
@Lexari0 feel free to check the PR and add any notes if you have, otherwise I'll merge it in the coming days :) You can grab the modified source and plop it into your project in case you're blocked by this.
