### ISSUE TITLE
Spawning location should be server-sided, not client-sided

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#247]
```gdscript

func _snap_to_spawn():
	var spawns = get_tree().get_nodes_in_group("Spawn Points")
	var idx = hash(player_id + respawn_count * 39) % spawns.size()
	var spawn = spawns[idx] as Node3D
	
	global_transform = spawn.global_transform
```

This runs on respawn, and on host/join.

Instead of running at respawn, it should run at death, and request by server the spawn point (TCP using different channel?)
More importantly, on join, the server should give some information like the spawn/starting location of the player, instead of the client going full self-determination. For this, I think like many other virtual functions (empty with `pass`), there should be a function which is empty which runs right before `NetworkTime.after_sync` and gives to the client important data which are not existing on the scene.

Examples being: Starting Location, the playerids of other players etc

**Comment by elementbound** [comment]
I'm sorry but I don't see the point. Could you elaborate? 

The function you've mentioned runs both on server and clients. The server is still the authority. The point of this function to return the same thing on every peer, so that no communication is needed to decide where to (re)spawn. 

The client can't cheat, because if the above function gets tampered with and returns some other position, the server's authority will override it. So all that would happen is a temp glitch where the client readjusts to the server's authoritative state.

**Comment by TheYellowArchitect** [comment]
You are right. This was one of the first issues I were to post (it was delayed :sweat_smile: ), and having only skimmed it instead of understanding what it really does, I thought spawn points are client-sided. Anyway, was used to server sending to clients for starting location, instead of being predetermined, and I didn't expect that server enforcement backup, it looks great now.

Sorry for the false flag.
