### ISSUE TITLE
Expand History Limit

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#248]
Currently, the variable `history_limit` covers BOTH state and inputs. They should be seperated. One variable for limit to states, a seperate one for limit to inputs.

Also, a value of -1, should make them unable to be erased. Yes, it will be costly, but for inputs it shouldnt be a problem and helps with debugging (and saving replays in the future)

Lastly, no idea what the below variable `_data` is for (in the class `RollbackFreshnessStore`), is it inputs or states?
Even type hint wouldn't help here because both states and inputs are dictionaries lol

```gdscript
func trim():
	while _data.size() > NetworkRollback.history_limit:
		_data.erase(_data.keys().min())
```

**Comment by elementbound** [comment]
> They should be seperated

Why?

If you have less inputs than state, state becomes the limiting factor - you can't rollback to ticks you don't have state for, even though you could use the input for resim. 

If you have less state than input, input becomes the limiting factor - even though you can rollback to a tick, you can't resim from there, since you have no input.

My point is that in terms of rollback, state and input are inseparable.

If this is for recording games ( like discussed in #251 ), I don't think keeping all states and/or inputs in memory is the right call. I think it would be better to have a separate class that can grab data from RollbackSynchronizer nodes and store data properly ( e.g. keep some in memory while the rest is being written to disk ). 

---

For `_data`, see its usage, from the same class:

```gdscript
func notify_processed(node: Node, tick: int):
	if not _data.has(tick):
		_data[tick] = {}
	
	_data[tick][node] = true
```

It stores each node processed per tick. Since we trim based on ticks ( i.e. it doesn't make sense to remember a tick until the end of times ), the first key is the tick, the second is the object itself that was processed.

**Comment by TheYellowArchitect** [comment]
You are right, thank you for the explanation, I didn't think it that way.

>Replay Manager 

Currently, there are 2 ways to do a replay manager. The first is for the server (or clients) to save all states locally. This is easy to implement but will have titanic file size, so a diff implementation must be done for it (e.g. #264 )
The other is to have the first state, save it, and then simply save the serialized inputs. More complicated, but still simple enough, and it's what all past games did (RTS, Doom etc)

>I think it would be better to have a separate class that can grab data from RollbackSynchronizer nodes and store data properly ( e.g. keep some in memory while the rest is being written to disk ).


How would you suggest to do this? The part where you keep in memory while the rest is being written to disk. I haven't tested with practical/real game states/inputs, but it should be easy to hold those serialized inputs.

Anyway, if you give me the technical details, I am willing to implement this after the other PRs are merged.
