### ISSUE TITLE
Client Input to be relayed exclusively through the server, instead of directly to clients

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#281]
If there are 40 players, and a client RPCs `submit_input` (RPC mode is "any_peer") that's a LOT of bandwidth as it sends the input to 40 players directly, instead of sending to the server and the server sends to the 40 clients. Not relaying the inputs should instakill a network.

What should happen is the inputs send the input exclusively to the server, and the server submits the input to the clients. So 40 inputs are sent to 1 peer ID (that being the server), and the server sends 40 inputs to each player.
The data sent is the same, but the connections are not. Each peer having a connection to 40 peers is bad.
This is not the same as broadcast_input which straight up disables sending input to other clients, and only the server receives it.

I suggest some kind of tag "Investigate/not confirmed" because this needs further investigation, and so feel free to close this, as unlike other issues, it's unconfirmed.
First of all, this is only valid in a P2P network. By default, clients can RPC any other client as long that RPC function has "any_peer". But does the below codeline close this issue?

```gdscript
	get_tree().get_multiplayer().server_relay = true
```

Or is the default setup, by default server/client instead of P2P? So sending inputs, it automatically goes through the server instead of sending directly to clients. If so, this issue is again, needless and must close.

**Comment by elementbound** [comment]
**Please refrain from opening issues based on hypotheticals**, otherwise I'll be forced to close these tickets without discussion in the future. If you're not sure how something in Godot works, please feel free to consult the docs, peruse their many support channels, or if you prefer the netfox community, feel free to just ask in our [Discord](https://discord.gg/xWGh4GskG5).

If you suspect that something's wrong, please either confirm it before opening an issue, or ask about it on the appropriate support channels. Instead of reporting it as an actual issue with netfox.

Going through these hypotheticals takes time away from maintenance, and usually doesn't bring much benefit to netfox itself. 

---

> If there are 40 players, and a client RPCs submit_input (RPC mode is "any_peer") that's a LOT of bandwidth as it sends the input to 40 players directly

That is *not* what "any_peer" does. Please read the relevant Godot [documentation](https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html#remote-procedure-calls).

> Each peer having a connection to 40 peers is bad.

This is also false. In a server-client setup ( which netfox is geared towards, and what is used in the examples ), the server has a dedicated connection to all clients, but clients only have a single connection each, to the server.

---

Closing issue. If you feel there's an actual issue around data flow, please do report it! But when doing so, make sure that you have confirmed the issue, and can share it in some tangible form.
