### ISSUE TITLE
Reduce bandwidth on RPCs by having arguments be single letter

### ISSUE THREAD

**Issue by warsang** [foxssake/netfox#290]
Hi!

Just a proposal as I was reading through https://github.com/jonathaneeckhout/jdungeon/blob/main/documentation/networkingsync.md  which has some interesting info on Godot RPCs; 

Godot sends the full argument name over the network when performing an RPC call.
While this makes the code a bit less readable, changing arguments to 1 letter should reduce the size of RPCs sent over network and improve bandwidth; You can always rename the arguments once received to something more readable or add a comment to make sure the code is easily maintainable.

**Comment by TheYellowArchitect** [comment]
>You may also note that argument names for these functions are a single letter. This is intentional due to Godot needing to send argument names when performing RPCs.

Thank you for sharing this. That's awful lol, I will go open a godot proposal for this

As for the rest of this issue, netfox with forest-brawl as tutorial must be as readable as possible, given the complexity of rollback. I think this optimization shoud be project-specific instead of being automatically applied to all RPC calls. 

That said, this optimization does have merit, so in the docs, or in some comment, there should be a suggestion to use single-letter RPC parameters :+1:

**Comment by Faless** [comment]
As explained in https://github.com/godotengine/godot-proposals/issues/10885 the statement is wrong.

Godot **does not** send the arguments names, **nor the function name**.

The RPC sends:

- The Node Network ID **OR** the node path (only if the node path has not been already exchanged)
- The function ID (reason why RPCs must match between server and client)
- The argument count
- The argument values

**Comment by elementbound** [comment]
Thanks for the note @warsang and thanks @Faless for clearing this up! Browsing around the [code] a bit seems to confirm this. Also created https://github.com/jonathaneeckhout/jdungeon/issues/262 so they can update their docs if wanted. 

[code]: https://github.com/godotengine/godot/blob/db66bd35af704fe0d83ba9348b8c50a48e51b2ba/modules/multiplayer/scene_rpc_interface.cpp#L168
