### ISSUE TITLE
`_simulated_nodes` should be an Array[Node], instead of a Dictionary

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#297]
Its key is a node, and its value is a boolean. But it never gets the value `false`. This variable is used only to check if a node is simulated, so it checks if the dictionary has that key. For simplicity and performance, this variable should be changed to `var _simulated_nodes: Array[Node]`

I would open a PR for this to save time, but too many rejected PRs

**Comment by elementbound** [comment]
No, it should not be. I *strongly* recommend asking questions instead of asserting how things should be implemented. 

`_simulated_nodes` is semantically a set of nodes. Since Godot doesn't have sets natively, I'm using a dictionary, whose keys act as a set. Searching through sets to check if they contain an item is generally faster than doing the same with an array, especially for larger data sets. Hence the choice to use a set.

I'll add a comment in `NetworkRollback.gd` to clarify, and close this issue.
