### ISSUE TITLE
Jittery player movement (using state machine) on a remote server

### ISSUE THREAD

**Issue by immails** [foxssake/netfox#303]
### :bug: Description

Movement, which is handled by a state machine, appears jittery/laggy (sudden unexpected rollbacks) while playing on a remote server. 

### Steps to reproduce

1. Implement a state machine for players
2. Implement OnAir and OnGround states (even without transitions)
3. Add to RollbackSynchronizer and TickInterpolator following properties: current_state (of state machine), velocity, position and gsp (ground speed)
4. Get a remote machine to run the game server

### Expected behavior

1. Expected sudden events like jumps or collisions to be smooth
2. Expected to not rollback on every sudden event

### Observed behavior

Observed while testing on a remote server:
1. Rollback happens on every collision, like:
- with a wall
- with a ground
2. Rollback happens when player jumps
https://github.com/user-attachments/assets/8f647039-221d-404e-9edd-2f15cd7ba287

Observed while testing on a localhosted server:
1. Rollback doesn't happen on collisions
2. Rollback doesn't happen on jumps
https://github.com/user-attachments/assets/c5b19096-3b00-4656-b841-81ca255e8c80

### Versions

* Godot version: *v4.3.stable.official [77dcf97d8]*
* netfox version: *v1.8.0*

### MRE

Available at https://gitlab.com/immails/Godot-4.3-netfox-MRP/

**Comment by elementbound** [comment]
Might be related to #302, just merged #315. I'll take a look at the MRP finally to confirm.

**Comment by elementbound** [comment]
Turns out it wasn't related :smile: As far as I can see, the state machine works well. There were two issues at play.

---

#### Raycasts and rollback

Raycasts only update in `_physics_process`, but their results were used during rollback. To fix this, simply call `force_raycast_update()` on them in `_rollback_tick`. Here's the snippet I used in `player.gd`:

```gdscript
func _rollback_tick(delta: float, _tick: int, _is_fresh: bool) -> void:
	var rays: Array[RayCast2D] = [
		left_ground_ray, right_ground_ray,
		LeftStepRay, RightStepRay,
		LeftWallRay, RightWallRay,
		angle_ray
	]
	
	for ray in rays:
		ray.force_update_transform()
		ray.force_raycast_update()
```

You can check whether `force_update_transform()` is needed. Also feel free to hardcode the calls instead of iterating over an array, might be slightly more efficient. You can also set `enabled` to `false` on the Raycasts, since they will be manually updated in the rollback tick loop.

---

#### Block on Wall?

Even with raycast updates, the player would glitch when running towards a wall and holding jump. It looked like it was getting stuck on a phantom collision for a second. This collision only happened on the client, never on the server, so the two disagreed, and the player glitched on reconciliation, when receiving state from the server.

I've disabled the *Block on Wall* option on the Player. I'm not that familiar with the setting itself, but it solved the issue apparently. 

---

Let me know if the above solves your issue!

**Comment by immails** [comment]
Issues are solved. Thank you 💞
