### ISSUE TITLE
State Machine example is broken

### ISSUE THREAD

**Issue by krazyjakee** [foxssake/netfox#327]
### Bug Description

Clients do not always receive state change notifications from other clients when using RewindableStateMachine. Specifically, state transitions like entering `IDLE` are sometimes not synchronized across all clients, leading to inconsistent animation states.

### Steps to reproduce

1. Run State Machine example
2. Move around and jump on multiple clients

### Expected behavior

1. All connected clients receive consistent state change messages from other players.
2. State transitions, such as moving to `IDLE`, should be applied across all clients.

### Observed behavior

1. State change messages are not consistently received by all clients.
2. Only the host and the client that triggers the state change receive the update, while other clients do not.

### Versions

* Godot version: 4.1
* netfox version: Main branch (not officially released)

### Notes

- Testing on a dedicated server setup may produce different results.
- The multiplayer-state-machine demo did not function as expected when hitting `host/join`.
- The current setup uses the latest Netfox version cloned from the main branch, not an official release.
- The issue occurs regardless of amount of latency

**Comment by TheYellowArchitect** [comment]
Uploading video confirmation 

https://github.com/user-attachments/assets/b9bbb894-a9f3-458f-8886-308a3dd16cdf

**Comment by krazyjakee** [comment]
Notes:
- Is the initial state being set using rollback? (i.e no enter/exit calls) - This would be a problem but potentially a different problem.
- When adding the character color and label text to the rollback synchronizer, it fixes the issue. It seems the state is being set but the enter and exit callbacks are not being called on the client. Do we just advise that all changes should be synced or should we dig deeper and ensure callbacks are run on the clients at the right time?

**Comment by elementbound** [comment]
I think the main issue is that transitions and the way the example is setup is confusing. 

State transition callbacks ( enter and exit ) are only called for peers which simulate the given state machine. This means the player who owns input for it, and the host who owns the state. The rest of the peers don't simulate the state machine, because they don't have the input to use to predict what happens ( and #321 is not done yet ). So they also don't trigger transition callbacks.

The example changes the label color on transition:
```gdscript
	state_machine.on_state_changed.connect(func (_old_state, new_state):
		if new_state.name:
			current_state_label.text = new_state.name
	)
```

And changes player color when entering a state:
```gdscript
func enter(_previous_state, _tick):
	character.set_color(Color.RED)
```

This means that the displayed data will only update when transitions are triggered. **This does not mean that state is not synchronized to clients.** This is why it is confusing imo.

---

First off, to clear the confusion, I think we can update the example project to always display the latest state, not the last transition. This is also important because due to rollback, we often don't re-run the latest state transition. We can also improve documentation to make this more explicit to people.

---

Then there's the question of running transition callbacks. What would be the preferred behavior here? Rollback ticks are only ran for objects that need it, which in turn means that the state machine is not always simulated, which ends up in the transitions not always being triggered.
